version: "3.9"

services:
  widgets-ms-red:
    image: maratmingazovr/widgets-ms:1.0
    container_name: widgets-ms-red
    ports:
      - "8090:8090"
    environment:
      MIRO_TOKEN: xxx
      DEFAULT_COLOR: RED
      SERVER_PORT: 8090

  widgets-ms-blue:
    image: maratmingazovr/widgets-ms:1.0
    container_name: widgets-ms-blue
    ports:
      - "8095:8095"
    environment:
      MIRO_TOKEN: xxx
      DEFAULT_COLOR: BLUE
      SERVER_PORT: 8095

  load-balancer:
    image: maratmingazovr/load-balancer-ms:1.0
    container_name: load-balancer-ms
    ports:
      - "8080:8080"
    depends_on:
      - widgets-ms-red
      - widgets-ms-blue